; начало области gpio
GPIO EQU 0x40020000

; порты GPIO
PORT_C EQU 0x800

; режимы работы gpio
GPIO_MODE_OUT    EQU 1
GPIO_MODE_AF     EQU 2
GPIO_MODE_IN     EQU 0
GPIO_MODE_ANALOG EQU 3

; режимы работы gpio
GPIO_MODE_PP    EQU 0
GPIO_MODE_PP_PU EQU 1
GPIO_MODE_PP_PD EQU 2

; отступы настройки портов
OTYPER  EQU 0x04
OSPEEDR EQU 0x08
PUPDR   EQU 0x0C
IDR     EQU 0x10
ODR     EQU 0x14 
BSRR    EQU 0x18
LCKR    EQU 0x1C
AFRL    EQU 0x20
AFRH    EQU 0x24

; адреса регистров настройки порта С
GPIOC_MODER   EQU (GPIO + PORT_C)
GPIOC_OTYPER  EQU (GPIOC_MODER + OTYPER) 
GPIOC_OSPEEDR EQU (GPIOC_MODER + OSPEEDR)  
GPIOC_PUPDR   EQU (GPIOC_MODER + PUPDR) 
GPIOC_IDR     EQU (GPIOC_MODER + IDR)
GPIOC_ODR     EQU (GPIOC_MODER + ODR)
GPIOC_BSRR    EQU (GPIOC_MODER + BSRR)
GPIOC_LCKR    EQU (GPIOC_MODER + LCKR)
GPIOC_AFRL    EQU (GPIOC_MODER + AFRL)
GPIOC_AFRH    EQU (GPIOC_MODER + AFRH)

; bit_word_addr = bit_band_base + (byte_offset x 32) + (bit_number × 4)
GPIO_ODR_BB EQU 0x42000000 + ((GPIOC_ODR & 0x00FFFFFFFF) * 32)

GPIOC_OUT_PIN_0_BB EQU GPIO_ODR_BB
GPIOC_OUT_PIN_1_BB EQU GPIO_ODR_BB + (1 * 4)
GPIOC_OUT_PIN_2_BB EQU GPIO_ODR_BB + (2 * 4)
GPIOC_OUT_PIN_3_BB EQU GPIO_ODR_BB + (3 * 4)
GPIOC_OUT_PIN_4_BB EQU GPIO_ODR_BB + (4 * 4)
GPIOC_OUT_PIN_5_BB EQU GPIO_ODR_BB + (5 * 4)
GPIOC_OUT_PIN_6_BB EQU GPIO_ODR_BB + (6 * 4)
GPIOC_OUT_PIN_7_BB EQU GPIO_ODR_BB + (7 * 4)
GPIOC_OUT_PIN_8_BB EQU GPIO_ODR_BB + (8 * 4)
GPIOC_OUT_PIN_9_BB EQU GPIO_ODR_BB + (9 * 4)
GPIOC_OUT_PIN_10_BB EQU GPIO_ODR_BB + (10 * 4)
GPIOC_OUT_PIN_11_BB EQU GPIO_ODR_BB + (11 * 4)
GPIOC_OUT_PIN_12_BB EQU GPIO_ODR_BB + (12 * 4)
GPIOC_OUT_PIN_13_BB EQU GPIO_ODR_BB + (13 * 4)
GPIOC_OUT_PIN_14_BB EQU GPIO_ODR_BB + (14 * 4)

 END