; начало области rcc
RCC  EQU 0x40023800

CR EQU 0

AHB1ENR EQU 0x30
RCC_AHB1ENR  EQU (RCC + AHB1ENR)

RCC_AHB1_GPIO_BB EQU 0x42000000 + ((RCC_AHB1ENR & 0x00FFFFFFFF) * 32)
; bit_word_addr = bit_band_base + (byte_offset x 32) + (bit_number × 4)
RCC_EN_GPIOA_BB EQU RCC_AHB1_GPIO_BB
RCC_EN_GPIOB_BB EQU RCC_AHB1_GPIO_BB + (1 * 4)
RCC_EN_GPIOC_BB EQU RCC_AHB1_GPIO_BB + (2 * 4)
RCC_EN_GPIOD_BB EQU RCC_AHB1_GPIO_BB + (3 * 4)
RCC_EN_GPIOE_BB EQU RCC_AHB1_GPIO_BB + (4 * 4)

RCC_EN_GPIOH_BB EQU RCC_AHB1_GPIO_BB + (7 * 4)

 END